[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'tpope/vim-unimpaired'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'tpope/vim-fugitive'
