[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# [[plugins]]
# repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
colorscheme tokyonight
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

# [[plugins]]
# repo = 'Shougo/ddu.vim'
# hook_add = '''
# call ddu#custom#patch_global({
# \   'ui': 'ff',
# \   'sources': [
# \     {
# \       'name': 'file_rec',
# \       'params': {
# \         'ignoredDirectories': ['.git', 'node_modules', 'vendor']
# \       }
# \     },
# \     { 'name': 'buffer' },
# \     {'name':'file','params':{}}
# \   ],
# \   'sourceOptions': {
# \     '_': {
# \       'matchers': ['matcher_substring'],
# \     },
# \   },
# \   'filterParams': {
# \     'matcher_substring': {
# \       'highlightMatched': 'Title',
# \     },
# \   },
# \   'kindOptions': {
# \     'file': {
# \       'defaultAction': 'open',
# \     },
# \   },
# \   'uiParams': {
# \     'ff': {
# \       'startFilter': v:true,
# \       'prompt': '> ',
# \     }
# \   },
# \ })


# call ddu#custom#patch_local('grep', {
# \   'sourceParams' : {
# \     'rg' : {
# \       'args': ['--column', '--no-heading', '--color', 'never'],
# \     },
# \   },
# \   'uiParams': {
# \     'filer': {
# \       'startFilter': v:false,
# \     }
# \   },
# \ })

# autocmd FileType ddu-ff call s:ddu_my_settings()
# function! s:ddu_my_settings() abort
#   nnoremap <buffer><silent> <CR>
#     \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>

#   nnoremap <buffer><silent> <Space>
#     \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'open', 'params': {'command': 'split'}})<CR>

#   nnoremap <buffer><silent> a
#     \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>

#   nnoremap <buffer><silent> p
#     \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>

#   nnoremap <buffer><silent> <Esc>
#     \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
# endfunction

# autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
# function! s:ddu_filter_my_settings() abort
#   nnoremap <buffer> <CR>
#   \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
#   nnoremap <buffer><silent> q
#   \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
#   inoremap <buffer> <CR>
#   \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
#   inoremap <buffer><silent> <C-j>
#   \ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)")<CR>
#   inoremap <buffer><silent> <C-k>
#   \ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)")<CR>
# endfunction

# nmap <silent> ;f <Cmd>call ddu#start({})<CR>
# nmap <silent> ;b <Cmd>call ddu#start({'sources': [{'name': 'buffer'}]})<CR>
# nmap <silent> ;g <Cmd>call ddu#start({
# \   'name': 'grep',
# \   'volatile': v:true,
# \   'sources': [{
# \     'name': 'rg',
# \     'options': {'matchers': []},
# \   }],
# \   'uiParams': {'ff': {
# \     'ignoreEmpty': v:false,
# \     'autoResize': v:false,
# \   }},
# \ })<CR>

# "ddu keymapping.
# nnoremap <SID>[ug] <Nop>
# nmap ,u <SID>[ug]

# nnoremap <silent> <SID>[ug]m :<C-u>Ddu mr<CR>
# nnoremap <silent> <SID>[ug]b :<C-u>Ddu buffer<CR>
# nnoremap <silent> <SID>[ug]r :<C-u>Ddu register<CR>
# nnoremap <silent> <SID>[ug]n :<C-u>Ddu file -source-param-new -volatile<CR>
# '''

# [[plugins]]
# repo = 'Shougo/ddu-source-file'

# [[plugins]]
# repo = 'Shougo/ddu-kind-file'

# [[plugins]]
# repo = 'Shougo/ddu-ui-ff'

# [[plugins]]
# repo = 'Shougo/ddu-column-filename'

# [[plugins]]
# repo = 'Shougo/ddu-source-file_rec'

# [[plugins]]
# repo = 'Shougo/ddu-filter-matcher_substring'

# [[plugins]]
# repo = 'Shougo/ddu-commands.vim'

# [[plugins]]
# repo = 'Shun/ddu-source-rg'

# [[plugins]]
# repo = 'Shun/ddu-source-buffer'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign='left'
'''

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'neovim/nvim-lspconfig'
#depends = ['mason.nvim', 'mason-lspconfig.nvim']
#on_ft = ['ruby', 'typescript', 'javascript']
#hook_add = '''
#lua <<EOF
#  local mason_lspconfig = require("mason")
#  require("mason-lspconfig").setup()
#
#  mason_lspconfig.setup({
#    ensure_installed = {
#      'tsserver',
#      'eslint',
#    },
#    automatic_installation = true,
#  })
#
#  -- Mappings.
#  -- See `:help vim.diagnostic.*` for documentation on any of the below functions
#  local opts = { noremap=true, silent=true }
#  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
#  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
#  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
#  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
#
#  local on_attach = function(client, bufnr)
#    -- Enable completion triggered by <c-x><c-o>
#    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
#
#   end
#
#  local lsp_flags = {
#    debounce_text_changes = 150,
#  }
#  local lspconfig = require('lspconfig')
#  local servers = { 'solargraph', 'tsserver', 'vuels' }
#  for _, lsp in ipairs(servers) do
#    lspconfig[lsp].setup{
#        flags = {
#      debounce_text_changes = 150,
#      },
#    settings = {
#      solargraph = {
#        diagnostics = false,
#        commandPath = '/Users/kentaro/.asdf/shims/solargraph',
#        autostart = false
#      }
#    }
#    }
#  end
#EOF
#
#let g:LanguageClient_serverCommands = {
#        \ 'ruby': ['solargraph', 'stdio'],
#        \ }
#
#nnoremap <silent> gD <cmd>lua vim.lsp.buf.declaration()<CR>
#nnoremap <silent> gd <cmd>lua vim.lsp.buf.definition()<CR>
#nnoremap <silent> K <cmd>lua vim.lsp.buf.hover()<CR>
#nnoremap <silent> gi <cmd>lua vim.lsp.buf.implementation()<CR>
#nnoremap <silent> <C-k> <cmd>lua vim.lsp.buf.signature_help()<CR>
#nnoremap <silent> <space>D <cmd>lua vim.lsp.buf.type_definition()<CR>
#nnoremap <silent> <space>rn <cmd>lua vim.lsp.buf.rename()<CR>
#nnoremap <silent> <space>ca <cmd>lua vim.lsp.buf.code_action()<CR>
#nnoremap <silent> gr <cmd>lua vim.lsp.buf.references()<CR>
#nnoremap <silent> <space>f <cmd>lua vim.lsp.buf.format({ async = true })<CR>
#'''
#
#[[plugins]]
#repo = 'williamboman/mason.nvim'
#
#[[plugins]]
#repo = 'williamboman/mason-lspconfig.nvim'
#depends = ['mason.nvim']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['ruby','typescript','javascript']
hook_add = '''
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'ruby': ['rubocop']
\}
let g:ale_pattern_options = {
\   '.*.cpp$': {'ale_enabled': 0},
\}
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
# on_i = 1
merged = '0'
# hook_source = 'call coil398#init#coc#hook_source()'

# [[plugins]]
# repo = 'junegunn/fzf'
# build = './install --all'
# merged = '0'

[[plugins]]
repo = 'jeetsukumaran/vim-buffergator'
hook_add = '''
let g:buffergator_suppress_keymaps = 1
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#default_hidden = 1
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {
      'lua'
    }
  },
  ensure_installed = { "cpp", "lua", "vim", "vimdoc", "query", "ruby", "javascript", "vue", "scss", "pug", "json", "html" },
}
EOF
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsSnippetDirectories=['coc/ultisnips']
  let g:UltiSnipsExpandTrigger="<Down>"
'''

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'bogado/file-line'

[[plugins]]
repo = 'osyo-manga/vim-operator-stay-cursor'
hook_add = '''
map y <Plug>(operator-stay-cursor-yank)
'''

[[plugins]]
repo = 'kana/vim-operator-user'
