[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['vue']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf']

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'

[[plugins]]
repo ='folke/trouble.nvim'
on_lua ='trouble'
hook_add="""
lua << EOF
require("trouble").setup({
  icons = false
})
EOF
"""

[[plugins]]
repo = 'tpope/vim-rhubarb'
